export const BALANCE = {
  saveVersion: 2,
  start: {
    money: 100000,
    reputation: 10,
  },
  time: {
    secondsPerWeekAt1x: 10,
  },
  employee: {
    pointsPerWeek: 0.02,
    workCycleWeeks: 1,
  },
  production: {
    initialInventory: {
      code: 6,
      design: 6,
      ops: 4,
      support: 4,
    },
    roleBaseOutput: {
      developer: { code: 10, design: 1, ops: 1, support: 0.5 },
      manager: { code: 1.5, design: 2.5, ops: 3, support: 3 },
      qa: { code: 1, design: 0.5, ops: 2.5, support: 6 },
      security: { code: 1, design: 0.25, ops: 6.5, support: 1.5 },
      marketing: { code: 0.5, design: 5.5, ops: 0.75, support: 2 },
    },
    outputModel: {
      experienceBase: 0.65,
      experienceRange: 0.75,
      moraleBase: 0.75,
      moraleRange: 0.45,
      burnoutDivisor: 180,
      burnoutMin: 0.3,
      talentBase: 0.85,
      talentRange: 0.55,
    },
    requirements: {
      installMultiplier: 0.85,
      upgradePerLevelMultiplier: 0.3,
      minimumUnits: 1,
    },
  },
  economy: {
    baseRevenueScale: 18000,
    infrastructureRate: 0.03,
    techComplexityCostMult: 500,
  },
  events: {
    lifecycleScale: {
      prototype: 0.15,
      beta: 0.3,
      release: 0.6,
      growth: 0.85,
      maturity: 1.0,
      decline: 1.0,
    },
    techExposure: {
      base: 0.4,
      perTech: 0.15,
      cap: 1.0,
    },
    noEventBase: 0.2,
    noEventExtraAtLowProgress: 0.6,
    oneEventShareFromRemainder: 0.75,
    penaltyMin: 0.2,
  },
  product: {
    qualityPerDevPerWeek: 0.008,
    qualityPerQaPerWeek: 0.005,
    audiencePerMarketingPerWeek: 0.012,
    releaseStageIndex: 2,
    releaseToGrowthWeeks: 8,
    releaseQualityThreshold: 0.5,
    growthToMaturityWeeks: 16,
    maturityToDeclineWeeks: 24,
    declineQualityLossPerWeek: 0.005,
    declineQualityFloor: 0.1,
    declineAudienceLossPerWeek: 0.008,
    declineAudienceFloor: 0,
  },
  team: {
    levelPenaltyPerLevel: 0.3,
    baseExperienceGainPerWeek: 1,
    developerExperienceBonusPerWeek: 0.5,
    teamSizeStressThreshold: 3,
    teamSizeStressPerMember: 0.8,
    levelStressPerLevel: 1.5,
    riskLoadMultiplier: 12,
    moraleRecoveryFactor: 0.06,
    isoRecoveryMultiplier: 10,
    moraleProfitBonus: 1.5,
    moraleLossBaseOnNegativeProfit: 2,
    moraleLossPerLevelOnNegativeProfit: 0.5,
    burnoutEffectHighThreshold: 70,
    burnoutEffectMidThreshold: 40,
    burnoutEffectLowThreshold: 20,
    burnoutEffectHighPenalty: -4,
    burnoutEffectMidPenalty: -2,
    burnoutEffectLowBonus: 1,
    autoQuitBurnoutThreshold: 95,
  },
  simulation: {
    maxFastForwardWeeks: 520,
    reasonLog: {
      profitDeltaThreshold: 100,
      qualityDeltaThreshold: 0.01,
      demandDeltaThreshold: 0.01,
      riskDeltaThreshold: 0.01,
    },
  },
  progression: {
    bankruptcyThreshold: -50000,
    ipoMoneyThreshold: 500000,
    ipoReputationThreshold: 80,
    marketDominanceReputation: 95,
    marketDominanceQuality: 0.9,
  },
} as const;

export type BalanceConfig = typeof BALANCE;
