export const BALANCE = {
  saveVersion: 6,
  start: {
    money: 100000,
    reputation: 10,
  },
  time: {
    secondsPerWeekAt1x: 10,
  },
  employee: {
    pointsPerWeek: 0.02,
    workCycleWeeks: 1,
  },
  production: {
    initialInventory: {
      code: 6,
      design: 6,
      ops: 4,
      support: 4,
    },
    roleBaseOutput: {
      developer: { code: 10, design: 1, ops: 1, support: 0.5 },
      manager: { code: 1.5, design: 2.5, ops: 3, support: 3 },
      qa: { code: 1, design: 0.5, ops: 2.5, support: 6 },
      security: { code: 1, design: 0.25, ops: 6.5, support: 1.5 },
      marketing: { code: 0.5, design: 5.5, ops: 0.75, support: 2 },
    },
    outputModel: {
      experienceBase: 0.65,
      experienceRange: 0.75,
      moraleBase: 0.75,
      moraleRange: 0.45,
      burnoutDivisor: 180,
      burnoutMin: 0.3,
      talentBase: 0.85,
      talentRange: 0.55,
    },
    requirements: {
      installMultiplier: 0.85,
      upgradePerLevelMultiplier: 0.3,
      minimumUnits: 1,
    },
  },
  infrastructure: {
    demandModel: {
      minimum: { web: 3, db: 2, cache: 1.5 },
      webTrafficDivisor: 180,
      webActiveDivisor: 4200,
      dbActiveDivisor: 2600,
      dbPayingDivisor: 820,
      cacheTrafficDivisor: 250,
      cacheActiveDivisor: 5200,
    },
    latency: {
      baseMs: 95,
      perLoadMs: 50,
      overloadQuadraticMs: 180,
      outageExtraMs: 240,
    },
    cloud: {
      tiers: [
        { tier: 1, capacity: { web: 55, db: 40, cache: 48 }, baseCost: 1600, variableCostPerLoad: 420 },
        { tier: 2, capacity: { web: 90, db: 70, cache: 82 }, baseCost: 3200, variableCostPerLoad: 560 },
        { tier: 3, capacity: { web: 150, db: 120, cache: 135 }, baseCost: 6200, variableCostPerLoad: 760 },
      ] as const,
      upgradeCost: [0, 18000, 36000] as const, // index == tier-1
    },
    own: {
      baseCapacity: { web: 30, db: 24, cache: 26 },
      expandStep: { web: 14, db: 10, cache: 12 },
      expandMoneyCost: { web: 8200, db: 7800, cache: 7600 },
      expandOpsCost: { web: 22, db: 20, cache: 18 },
      maintenanceCostPerUnit: 32,
    },
    risk: {
      ownHostingBaseRisk: 0.05,
      cloudBaseRisk: 0.018,
      overloadRiskScale: 0.55,
      businessRiskScale: 0.13,
      cloudRiskReduction: 0.82,
    },
    degradation: {
      overloadScale: 0.13,
      latencyThresholdMs: 240,
      latencyScale: 0.00065,
      outagePenalty: 0.11,
      maxDegradation: 0.34,
      productImpact: {
        trafficScale: 0.065,
        conversionScale: 0.095,
        churnScale: 0.17,
        satisfactionScale: 0.38,
        activeScale: 0.009,
        payingScale: 0.007,
        outageTrafficShock: 0.018,
        outageActiveShock: 0.009,
        outagePayingShock: 0.008,
      },
    },
  },
  support: {
    slaTargetWeeks: 2,
    ticketGeneration: {
      basePerActiveUser: 0.008,
      overloadScale: 16,
      outageSpike: 40,
      churnScale: 0.055,
    },
    teamCapacityByRole: {
      developer: 1.6,
      manager: 4.2,
      qa: 10,
      security: 2.8,
      marketing: 2.1,
    },
    teamEfficiency: {
      min: 0.45,
      max: 1.65,
      base: 0.75,
      experienceDivisor: 200,
      moraleDivisor: 250,
      burnoutDivisor: 280,
    },
    inventorySupport: {
      maxSharePerWeek: 0.65,
      ticketsPerUnit: 5,
    },
    queueDynamics: {
      waitDecayWhenClear: 0.35,
      waitCarry: 0.7,
      waitRatioDivisor: 2.4,
      backlogResolvedScale: 2.6,
      backlogBuffer: 35,
    },
    penalty: {
      backlogScale: 0.06,
      waitBeyondSlaScale: 0.018,
      maxPenalty: 0.16,
    },
    burst: {
      moneyCostPerTicket: 14,
      maxTicketsPerAction: 120,
      supportUnitsPerTicket: 0.14,
    },
  },
  competition: {
    initial: {
      competitorsCount: 4,
      usersMin: 120,
      usersRange: 480,
      growthMin: 0.008,
      growthRange: 0.03,
      qualityMin: 0.3,
      qualityRange: 0.2,
      reputationMin: 10,
      reputationRange: 24,
      pressureMin: 0.05,
      pressureRange: 0.07,
    },
    lifecyclePressureScale: {
      prototype: 0.22,
      beta: 0.45,
      release: 0.68,
      growth: 0.84,
      maturity: 0.92,
      decline: 0.78,
    },
    growthModel: {
      reputationPressureDivisor: 2200,
      qualityPressureScale: 0.014,
      randomNoiseScale: 0.01,
      growthFloor: -0.015,
      growthCap: 0.075,
      usersFloor: 80,
      qualityNoiseScale: 0.01,
      qualityGrowthInfluence: 0.015,
      qualityFloor: 0.2,
      qualityCap: 0.9,
      reputationGrowthScale: 9,
      reputationNoiseScale: 1.1,
      reputationFloor: 5,
      reputationCap: 99,
      pressureBase: 0.04,
      pressureUsersDivisor: 140000,
      pressureQualityScale: 0.045,
      pressureFloor: 0.03,
      pressureCap: 0.24,
      blendPrevGrowth: 0.9,
      blendNewGrowth: 0.1,
      smoothedGrowthFloor: 0.002,
      smoothedGrowthCap: 0.085,
      marketPressureCap: 0.3,
    },
    playerImpact: {
      trafficPenaltyScale: 0.028,
      conversionPenaltyScale: 0.012,
      churnBoostScale: 0.007,
      satisfactionPenaltyScale: 0.01,
      activeUsersPenaltyScale: 0.0025,
      payingUsersPenaltyScale: 0.002,
      bottleneckPressureThreshold: 0.17,
    },
    pressureEvents: {
      surgeShareThreshold: 0.14,
      surgePressureThreshold: 0.18,
      surgeChance: 0.12,
      surgeTrafficMultiplier: 0.985,
      surgeSatisfactionPenalty: 0.005,
      surgeReputationDelta: -1,
      breakthroughRankRequired: 1,
      breakthroughChance: 0.17,
      breakthroughTrafficMultiplier: 1.015,
      breakthroughSatisfactionBonus: 0.006,
      breakthroughReputationDelta: 1,
    },
    mna: {
      buyUserBase: {
        minCost: 3800,
        usersCost: 4.2,
        reputationCost: 60,
        minTargetUsers: 80,
        transferMin: 30,
        transferShareBase: 0.16,
        transferShareRange: 0.1,
        pressureReduction: 0.02,
        reputationReward: 3,
        payingShareMin: 0.03,
        payingShareFromConversionScale: 0.38,
      },
      acquireTechnology: {
        minCost: 5600,
        qualityCost: 6200,
        reputationCost: 90,
        competitorQualityPenalty: 0.04,
        reputationReward: 4,
      },
      acquiHire: {
        minCost: 6400,
        baseCost: 4500,
        usersCost: 1.8,
        maxHires: 3,
        experienceBonus: 18,
        moraleBonus: 8,
        competitorUsersMultiplier: 0.9,
        pressureReduction: 0.025,
        reputationReward: 3,
      },
      brandBoost: {
        minCost: 3600,
        baseCost: 3000,
        reputationCost: 65,
        competitorReputationPenalty: 4,
        pressureReduction: 0.02,
        trafficMultiplier: 1.09,
        satisfactionBonus: 0.015,
        reputationReward: 5,
      },
    },
  },
  economy: {
    baseRevenueScale: 18000,
    infrastructureRate: 0.03,
    techComplexityCostMult: 500,
  },
  events: {
    lifecycleScale: {
      prototype: 0.15,
      beta: 0.3,
      release: 0.6,
      growth: 0.85,
      maturity: 1.0,
      decline: 1.0,
    },
    techExposure: {
      base: 0.4,
      perTech: 0.15,
      cap: 1.0,
    },
    noEventBase: 0.2,
    noEventExtraAtLowProgress: 0.6,
    oneEventShareFromRemainder: 0.75,
    penaltyMin: 0.2,
  },
  product: {
    qualityPerDevPerWeek: 0.008,
    qualityPerQaPerWeek: 0.005,
    audiencePerMarketingPerWeek: 0.012,
    releaseStageIndex: 2,
    releaseToGrowthWeeks: 8,
    releaseQualityThreshold: 0.5,
    growthToMaturityWeeks: 16,
    maturityToDeclineWeeks: 24,
    declineQualityLossPerWeek: 0.005,
    declineQualityFloor: 0.1,
    declineAudienceLossPerWeek: 0.008,
    declineAudienceFloor: 0,
  },
  team: {
    levelPenaltyPerLevel: 0.3,
    baseExperienceGainPerWeek: 1,
    developerExperienceBonusPerWeek: 0.5,
    teamSizeStressThreshold: 3,
    teamSizeStressPerMember: 0.8,
    levelStressPerLevel: 1.5,
    riskLoadMultiplier: 12,
    moraleRecoveryFactor: 0.06,
    isoRecoveryMultiplier: 10,
    moraleProfitBonus: 1.5,
    moraleLossBaseOnNegativeProfit: 2,
    moraleLossPerLevelOnNegativeProfit: 0.5,
    burnoutEffectHighThreshold: 70,
    burnoutEffectMidThreshold: 40,
    burnoutEffectLowThreshold: 20,
    burnoutEffectHighPenalty: -4,
    burnoutEffectMidPenalty: -2,
    burnoutEffectLowBonus: 1,
    autoQuitBurnoutThreshold: 95,
  },
  simulation: {
    maxFastForwardWeeks: 520,
    reasonLog: {
      profitDeltaThreshold: 100,
      qualityDeltaThreshold: 0.01,
      demandDeltaThreshold: 0.01,
      riskDeltaThreshold: 0.01,
    },
  },
  progression: {
    bankruptcyThreshold: -500000,
    ipoMoneyThreshold: 500000,
    ipoReputationThreshold: 80,
    marketDominanceReputation: 95,
    marketDominanceQuality: 0.9,
  },
  corporate: {
    valuation: {
      base: 120000,
      activeUserWeight: 24,
      payingUserWeight: 170,
      reputationWeight: 1500,
      profitWeight: 16,
      negativeProfitWeight: 7,
      min: 80000,
      max: 50000000,
    },
    rounds: {
      pre_seed: {
        minWeek: 4,
        minValuation: 100000,
        cash: 75000,
        equity: 0.12,
      },
      seed: {
        minWeek: 12,
        minValuation: 250000,
        cash: 180000,
        equity: 0.15,
      },
      series_a: {
        minWeek: 28,
        minValuation: 900000,
        cash: 500000,
        equity: 0.18,
      },
      growth: {
        minWeek: 52,
        minValuation: 2500000,
        cash: 1200000,
        equity: 0.2,
      },
    },
    buyback: {
      premium: 1.3,
      minPct: 0.01,
      maxPctPerAction: 0.1,
    },
    boardPressure: {
      investorEquityFreeBand: 0.16,
      investorEquityScale: 1.6,
      lowGrowthThreshold: 0.015,
      lowGrowthPenalty: 0.12,
      negativeProfitPenalty: 0.1,
      highChurnThreshold: 0.12,
      highChurnPenalty: 0.08,
      highSatisfactionThreshold: 0.75,
      highSatisfactionRelief: 0.06,
      pressureCarry: 0.65,
      repPenaltyScale: 2.8,
      riskPenaltyScale: 0.06,
    },
    boardGoals: {
      minInvestorEquityToActivate: 0.08,
      defaultDeadlineWeeks: 10,
      cooldownWeeks: 8,
      rewardMoneyBase: 12000,
      rewardMoneyPressureScale: 9000,
      rewardReputationBase: 3,
      rewardReputationPressureScale: 4,
      reliefBase: 0.08,
      reliefPressureScale: 0.18,
      penaltyReputationBase: 4,
      penaltyReputationPressureScale: 6,
      penaltyPressureBase: 0.08,
      penaltyPressureScale: 0.14,
      activeUsersMinTarget: 1000,
      activeUsersStretchRatio: 1.22,
      satisfactionMinTarget: 0.68,
      satisfactionStretchDelta: 0.08,
      churnMaxTarget: 0.1,
      profitMinTarget: 2500,
      profitStretchRatio: 1.4,
    },
  },
} as const;

export type BalanceConfig = typeof BALANCE;
